#pragma once
#include "CoreMinimal.h"
#include "EVoiceKey.generated.h"

UENUM(BlueprintType)
enum class EVoiceKey : uint8 {
    Empty,
    FriendlyThrowingGrenade,
    FriendlyThrowingSmoke,
    FriendlyReloading,
    GrenadeIncoming,
    FriendlyGettingHit,
    FriendlyGettingShotAt,
    FriendlyGettingShotAt_Sniper,
    FriendlyDiesNearby,
    YouGetHit,
    YouGettingShotAt,
    YouGettingShotAt_Sniper,
    YouGetAKill,
    YouGetAKill_Naded,
    YouGetAKill_Headshot,
    YouGetAKill_Knifed,
    Promoted,
    DOMStartInstructions,
    DOMBeingDominated,
    DOMHoldingAllFlags,
    DOMTakenA,
    DOMTakenB,
    DOMTakenC,
    DOMLostA,
    DOMLostB,
    DOMLostC,
    CTFStartInstructions,
    CTFYourTeamCaptures,
    CTFTheirTeamCaptures,
    CTFTheyPickupYourFlag,
    CTFYouPickupTheirFlag,
    WRTStartInstructions,
    TDMStartInstructions,
    HQStartInstructions,
    HQYourTeamCaptures,
    HQTheirTeamCaptures,
    HQObjectiveLocated,
    HQObjectiveUnlocked,
    HQYourTeamDestroyed,
    HQTheirTeamDestroyed,
    HQYourTeamSecured,
    HQTheirTeamSecured,
    GlobalHalfwayToVictory,
    GlobalEnemyHalfwayToVictory,
    GlobalOneMinuteLeftWinning,
    GlobalOneMinuteLeftLosing,
    GlobalLeadLost,
    GlobalLeadTaken,
};

